version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
      docker: 18
    commands:
      - echo "Installing Maven..."
      - curl -sSL https://apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz | tar -xz -C /usr/local
      - export PATH=/usr/local/apache-maven-3.8.6/bin:$PATH
      - echo "Maven installed"

  pre_build:
    commands:
      - echo "Building Spring Boot WAR..."
      - mvn clean package -DskipTests

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t spring-boot-app .
      - docker tag spring-boot-app:latest $DOCKER_HUB_USERNAME/mywebsite:cicd

  post_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_USERNAME --password-stdin
      - echo "Pushing Docker image to Docker Hub..."
      - docker push $DOCKER_HUB_USERNAME/mywebsite:cicd

artifacts:
  files:
    - '*/'
