name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ashutoshbhakare/kucl22
      KUBECONFIG_PATH: /tmp/myconfig

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ github.run_number }} .

      - name: Tag and Push Docker Image
        run: |
          docker tag $IMAGE_NAME:${{ github.run_number }} $IMAGE_NAME:${{ github.run_number }}
          docker push $IMAGE_NAME:${{ github.run_number }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $KUBECONFIG_PATH
          export KUBECONFIG=$KUBECONFIG_PATH

      - name: Deploy to Kubernetes
        run: |
          sed -i 's,docker.io/httpd,${IMAGE_NAME}:${{ github.run_number }},' deployment.yaml
          kubectl apply -f deployment.yaml
